name: setup

on:
  workflow_call
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - name: clone repo
      uses: actions/checkout@v4
    - name: set up terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.4
    - name: Initialise
      run: terraform init
      shell: /usr/bin/zsh -e {0}
    #- name: Upload
      #uses: actions/upload-artifact@v1
      #with:
        #name: test.tf
        #path: test.tf
